### ISSUE TITLE
Calling GetTags for Android results in NullPointerException

### ISSUE THREAD

**Issue by vsayer** [one-signal/OneSignal-Xamarin-SDK#4]
Calling GetTags for Xamarin.Android results in the following exception:

[mono] Unhandled Exception:
[mono] Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
[mono]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x57ffbdc0 + 0x00024> in <filename unknown>:0 
[mono]   at Android.Runtime.JNIEnv.CallStaticVoidMethod (IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) <0x5703b098 + 0x000bf> in <filename unknown>:0 
[mono]   at Com.OneSignal.Android.OneSignal.GetTags (IGetTagsHandler p0) <0x57ffae70 + 0x0012f> in <filename unknown>:0 
[mono]   at Com.OneSignal.OneSignalAndroid.GetTags () <0x57ffae18 + 0x0001b> in <filename unknown>:0 
[mono]   at Com.OneSignal.OneSignal.GetTags (Com.OneSignal.TagsAvailable tagsAvailableDelegate) <0x57ffad98 + 0x0003f> in <filename unknown>:0 
[mono]   at Example.Shared.Application.Droid.MainActivity.RunTests () <0x57fa8380 + 0x003b3> in <filename unknown>:0 
[mono]   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x57fa8228 + 0x0009b> in <filename unknown>:0 
[mono]   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x57fa7d80 + 0x001f3> in <filename unknown>:0 
[mono]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x57fa7d28 + 0x0002b> in <filename unknown>:0 
[mono]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x57fa7c18 + 0x0005b> in <filename unknown>:0 
[mono]   at System.Threading.ThreadHelper.ThreadStart () <0x57fa78f8 + 0x0002b> in <filename unknown>:0 
[mono]   --- End of managed exception stack trace ---
[mono] java.lang.NullPointerException
[mono] 	at com.onesignal.OneSignal.getTags(OneSignal.java:735)
[mono] 	at dalvik.system.NativeStart.run(Native Method)
[mono] 
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.RuntimeException: Exception of type 'Java.Lang.RuntimeException' was thrown.
[mono-rt]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x57ffbdc0 + 0x00024> in <filename unknown>:0 
[mono-rt]   at Android.Runtime.JNIEnv.CallStaticVoidMethod (IntPtr jclass, IntPtr jmethod, Android.Runtime.JValue* parms) <0x5703b098 + 0x000bf> in <filename unknown>:0 
[mono-rt]   at Com.OneSignal.Android.OneSignal.GetTags (IGetTagsHandler p0) <0x57ffae70 + 0x0012f> in <filename unknown>:0 
[mono-rt]   at Com.OneSignal.OneSignalAndroid.GetTags () <0x57ffae18 + 0x0001b> in <filename unknown>:0 
[mono-rt]   at Com.OneSignal.OneSignal.GetTags (Com.OneSignal.TagsAvailable tagsAvailableDelegate) <0x57ffad98 + 0x0003f> in <filename unknown>:0 
[mono-rt]   at Example.Shared.Application.Droid.MainActivity.RunTests () <0x57fa8380 + 0x003b3> in <filename unknown>:0 
[mono-rt]   at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) <0x57fa8228 + 0x0009b> in <filename unknown>:0 
[mono-rt]   at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x57fa7d80 + 0x001f3> in <filename unknown>:0 
[mono-rt]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, Boolean preserveSyncCtx) <0x57fa7d28 + 0x0002b> in <filename unknown>:0 
[mono-rt]   at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) <0x57fa7c18 + 0x0005b> in <filename unknown>:0 
[mono-rt]   at System.Threading.ThreadHelper.ThreadStart () <0x57fa78f8 + 0x0002b> in <filename unknown>:0 
[mono-rt]   --- End of managed exception stack trace ---
[mono-rt] java.lang.NullPointerException
[mono-rt] 	at com.onesignal.OneSignal.getTags(OneSignal.java:735)
[mono-rt] 	at dalvik.system.NativeStart.run(Native Method)

It may make sense that this occurs when nothing is stored in the remote DB, which is actually fixed in the latest Android SDK, however this is occurring even when there are tags stored remotely.

**Comment by vsayer** [comment]
https://github.com/one-signal/OneSignal-Xamarin-SDK/pull/6

**Comment by vsayer** [comment]
Resolved with https://github.com/one-signal/OneSignal-Xamarin-SDK/commit/e17bf95409c6cfedd717afca71c6a5f93b80a296
